"""Add delivery_fees to InvoiceItem

Revision ID: 0cc78fd03a74
Revises: 948af1a1295d
Create Date: 2025-06-18 20:02:37.779058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc78fd03a74'
down_revision = '948af1a1295d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fees', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_column('delivery_fees')

    # ### end Alembic commands ###
