"""Add invoice_date to Invoice

Revision ID: 948af1a1295d
Revises: d9fa265be8c3
Create Date: 2025-06-18 20:00:36.646814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948af1a1295d'
down_revision = 'd9fa265be8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('invoice_date')

    # ### end Alembic commands ###
